import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  centerFlex1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textBold: {fontWeight: 'bold'},
  displayNone: {display: 'none'},
  backgroundOpacity: {backgroundColor: '#000000cc'},
  backgroundLight: {backgroundColor: '#f1f1f1'},
  flex1: {flex: 1},
  alignFlexEnd: {alignItems: 'flex-end'},
  backgroundPrimary: {backgroundColor: '#5067FF'},
  tetxCenter: {textAlign: 'center'},
  marginR16: {marginRight: 16},
  marginH16: {marginHorizontal: 16},
  marginV8: {marginVertical: 8},
  marginV16: {marginVertical: 16},
  marginH8: {marginHorizontal: 8},
  flexRow: {flexDirection: 'row'},
  margin16: {margin: 16},
  margin8: {margin: 8},
  padding16: {padding: 16},
  avatarCenterLarge: {width: 250, height: 250, alignSelf: 'center'},
  listSearch: {
    marginTop: 120,
    backgroundColor: '#f8f8f8',
    position: 'absolute',
    width: '100%',
  },
  textRight: {textAlign: 'right'},
  contentContainer: {
    flexGrow: 1,
    padding: 16,
    justifyContent: 'center',
    backgroundColor: '#fafafa',
    alignItems: 'center',
  },
  contentCard: {
    backgroundColor: 'white',
    padding: 16,
    borderRadius: 10,
    elevation: 5,
    width: '100%',
    maxWidth: 480,
  },
  input: {marginVertical: 8, borderRadius: 5},
  radius5: {borderRadius: 5},
  alignCenter: {alignItems: 'center'},
  cartMenu: {backgroundColor: 'white', padding: 16, marginBottom: 16},
  textOnScan: {color: 'white', textAlign: 'center', margin: 24},
});
